// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Layout from "../Layout.res.mjs";
import * as DeckData from "../data/DeckData.res.mjs";
import * as CardDetail from "../components/CardDetail.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function DetailDeck(props) {
  var slug = props.slug;
  var deck = DeckData.decks.find(function (deck) {
        return deck.slug === slug;
      });
  return JsxRuntime.jsx(Layout.make, {
              children: deck !== undefined ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: deck.name,
                              className: "text-3xl font-bold text-gray-800 mb-4 text-center"
                            }),
                        JsxRuntime.jsx("div", {
                              children: deck.cards.map(function (card) {
                                    return JsxRuntime.jsx(CardDetail.make, {
                                                card: card
                                              });
                                  }),
                              className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4"
                            })
                      ]
                    }) : JsxRuntime.jsx("p", {
                      children: "Deck not found"
                    })
            });
}

var make = DetailDeck;

export {
  make ,
}
/* Layout Not a pure module */
