// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Login(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "Page de Connexion"
                  })
            });
}

var make = Login;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
