// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function NotFound(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "404 - Page non trouvé"
                  })
            });
}

var make = NotFound;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
