// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Layout from "../Layout.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function NotFound(props) {
  var errorType = props.errorType;
  var errorMessage = errorType === "unauthorized" ? "Vous n'êtes pas autorisé à accéder à cette page." : (
      errorType === "serverError" ? "Une erreur de serveur s'est produite." : (
          errorType === "notFound" ? "La page que vous cherchez n'existe pas." : "Une erreur inconnue s'est produite."
        )
    );
  return JsxRuntime.jsx(Layout.make, {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("h1", {
                                  children: "Erreur",
                                  className: "text-6xl font-bold text-gray-800 mb-4"
                                }),
                            JsxRuntime.jsx("p", {
                                  children: errorMessage,
                                  className: "text-2xl text-gray-600 mb-8"
                                }),
                            JsxRuntime.jsx("a", {
                                  children: "Retour à l'accueil",
                                  className: "text-blue-500 hover:text-blue-700",
                                  href: "/"
                                })
                          ],
                          className: "text-center"
                        }),
                    className: "flex items-center justify-center min-h-80"
                  })
            });
}

var make = NotFound;

export {
  make ,
}
/* Layout Not a pure module */
