// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Layout from "../Layout.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Singup(props) {
  return JsxRuntime.jsx(Layout.make, {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("form", {
                          children: [
                            JsxRuntime.jsx("input", {
                                  className: "mb-4 p-2 border border-gray-300 rounded",
                                  placeholder: "Nom",
                                  type: "text"
                                }),
                            JsxRuntime.jsx("input", {
                                  className: "mb-4 p-2 border border-gray-300 rounded",
                                  placeholder: "Mot de passe",
                                  type: "password"
                                }),
                            JsxRuntime.jsx("button", {
                                  children: "S'inscrire",
                                  className: "p-2 bg-blue-500 text-white rounded",
                                  type: "submit"
                                })
                          ],
                          className: "flex flex-col"
                        }),
                    className: "flex flex-col max-w-md mx-auto"
                  })
            });
}

var make = Singup;

export {
  make ,
}
/* Layout Not a pure module */
