// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UsersData from "../data/UsersData.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function User(props) {
  var id = props.id;
  var user = UsersData.users.find(function (u) {
        return u.id === id;
      });
  if (user !== undefined) {
    return JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("h1", {
                      children: user.name
                    })
              });
  } else {
    return JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("h1", {
                      children: "User not found"
                    })
              });
  }
}

var make = User;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
