// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CardDetail(props) {
  var card = props.card;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "w-full",
                      alt: card.name,
                      src: card.imageUrl
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: card.name,
                              className: "text-lg font-semibold text-gray-800"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Cost: " + String(card.cost),
                              className: "text-sm text-gray-600"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Power: " + String(card.power),
                              className: "text-sm text-gray-600"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Effect: " + card.effect,
                              className: "text-sm text-gray-600"
                            })
                      ],
                      className: "p-4"
                    })
              ],
              className: "max-w-sm rounded overflow-hidden shadow-lg bg-white transition-transform transform hover:scale-105"
            });
}

var make = CardDetail;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
