// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function DeckCard(props) {
  var deck = props.deck;
  var deckName = deck.name;
  var deckSlug = deck.slug;
  var cardCount = deck.cards.length.toString();
  var handleClick = function () {
    RescriptReactRouter.push("/deck/" + deck.slug);
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h2", {
                            children: deckName,
                            className: "text-lg font-semibold text-gray-800"
                          }),
                      JsxRuntime.jsxs("p", {
                            children: [
                              "Deck slug",
                              deckSlug
                            ],
                            className: "text-sm text-gray-600"
                          }),
                      JsxRuntime.jsxs("p", {
                            children: [
                              "Nombre de cartes",
                              cardCount
                            ],
                            className: "text-sm text-gray-600"
                          })
                    ],
                    className: "p-4"
                  }),
              className: "max-w-sm rounded overflow-hidden shadow-lg bg-white cursor-pointer transition-transform transform hover:scale-105",
              onClick: (function (param) {
                  handleClick();
                })
            });
}

var make = DeckCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
