// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Footer(props) {
  return JsxRuntime.jsx("footer", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("p", {
                            children: "© 2024 OnePieceCGPro. All rights reserved.",
                            className: "text-sm"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("a", {
                                    children: "Twitter",
                                    className: "mx-2 text-blue-400 hover:text-blue-600",
                                    href: "https://twitter.com"
                                  }),
                              JsxRuntime.jsx("a", {
                                    children: "Facebook",
                                    className: "mx-2 text-blue-600 hover:text-blue-800",
                                    href: "https://facebook.com"
                                  }),
                              JsxRuntime.jsx("a", {
                                    children: "Instagram",
                                    className: "mx-2 text-pink-400 hover:text-pink-600",
                                    href: "https://instagram.com"
                                  })
                            ],
                            className: "mt-4"
                          })
                    ],
                    className: "container mx-auto text-center"
                  }),
              className: "bg-gray-800 text-white py-6"
            });
}

var make = Footer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
