// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Navbar from "./Navbar.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Layout(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Navbar.make, {}),
                props.children
              ]
            });
}

var make = Layout;

export {
  make ,
}
/* Navbar Not a pure module */
