// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DeckCard from "./DeckCard.res.mjs";
import * as DeckData from "../data/DeckData.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ListDeck(props) {
  return JsxRuntime.jsx("div", {
              children: DeckData.decks.map(function (deck) {
                    return JsxRuntime.jsx(DeckCard.make, {
                                deck: deck
                              });
                  }),
              className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4"
            });
}

var make = ListDeck;

export {
  make ,
}
/* DeckCard Not a pure module */
