// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Navbar(props) {
  return JsxRuntime.jsx("nav", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("img", {
                                  className: "h-10 w-auto",
                                  alt: "One Piece CG Pro Logo",
                                  src: "https://static.wixstatic.com/media/57a197_e334385962ac4203abe6390f3b6ff4c6~mv2.png"
                                }),
                            className: "flex items-center"
                          }),
                      JsxRuntime.jsxs("ul", {
                            children: [
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: "Sing Up",
                                          className: "text-gray-700 hover:text-blue-500",
                                          onClick: (function (param) {
                                              RescriptReactRouter.push("/connexion");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: "Login",
                                          className: "text-gray-700 hover:text-blue-500",
                                          onClick: (function (param) {
                                              RescriptReactRouter.push("/login");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: "Mon Navire",
                                          className: "text-gray-700 hover:text-blue-500",
                                          onClick: (function (param) {
                                              RescriptReactRouter.push("/mon-navire");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("button", {
                                          children: "Decks",
                                          className: "text-gray-700 hover:text-blue-500",
                                          onClick: (function (param) {
                                              RescriptReactRouter.push("/decks");
                                            })
                                        })
                                  })
                            ],
                            className: "flex space-x-4"
                          })
                    ],
                    className: "container mx-auto flex items-center justify-between p-4"
                  }),
              className: "bg-white shadow-md"
            });
}

var make = Navbar;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
