// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function PopUp(props) {
  var onClose = props.onClose;
  var match = React.useState(function () {
        return true;
      });
  if (!match[0]) {
    return null;
  }
  var setIsVisible = match[1];
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h2", {
                            children: "Alerte",
                            className: "text-xl font-bold text-red-600 mb-4"
                          }),
                      JsxRuntime.jsx("p", {
                            children: props.message,
                            className: "text-gray-700 mb-4"
                          }),
                      JsxRuntime.jsx("button", {
                            children: "Fermer",
                            className: "p-2 bg-blue-500 text-white rounded",
                            onClick: (function (_event) {
                                setIsVisible(function (param) {
                                      return false;
                                    });
                                onClose();
                              })
                          })
                    ],
                    className: "bg-white p-6 rounded shadow-lg text-center"
                  }),
              className: "fixed top-0 left-0 w-full h-full flex items-center justify-center bg-black bg-opacity-50"
            });
}

var make = PopUp;

export {
  make ,
}
/* react Not a pure module */
