// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "../pages/Login.res.mjs";
import * as LoginContext from "./LoginContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ProtectedRoute(props) {
  var match = LoginContext.useContext();
  if (match.isLogged) {
    return props.children;
  } else {
    return JsxRuntime.jsx(Login.make, {});
  }
}

var make = ProtectedRoute;

export {
  make ,
}
/* Login Not a pure module */
