// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./pages/Home.res.mjs";
import * as User from "./pages/User.res.mjs";
import * as Login from "./pages/Login.res.mjs";
import * as Singup from "./pages/Singup.res.mjs";
import * as NotFound from "./pages/NotFound.res.mjs";
import * as LoginContext from "./components/LoginContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var tmp;
  if (match) {
    switch (match.hd) {
      case "connexion" :
          tmp = match.tl ? JsxRuntime.jsx(NotFound.make, {}) : JsxRuntime.jsx(Singup.make, {});
          break;
      case "login" :
          tmp = match.tl ? JsxRuntime.jsx(NotFound.make, {}) : JsxRuntime.jsx(Login.make, {});
          break;
      case "user" :
          var match$1 = match.tl;
          tmp = match$1 && !match$1.tl ? JsxRuntime.jsx(User.make, {
                  id: match$1.hd
                }) : JsxRuntime.jsx(NotFound.make, {});
          break;
      default:
        tmp = JsxRuntime.jsx(NotFound.make, {});
    }
  } else {
    tmp = JsxRuntime.jsx(Home.make, {});
  }
  return JsxRuntime.jsx(LoginContext.DefaultProvider.make, {
              children: tmp
            });
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
