// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Footer from "./components/Footer.res.mjs";
import * as Navbar from "./components/Navbar.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Layout(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Navbar.make, {}),
                JsxRuntime.jsx("div", {
                      children: props.children,
                      className: "container mt-5 mb-5 mx-auto"
                    }),
                JsxRuntime.jsx(Footer.make, {})
              ]
            });
}

var make = Layout;

export {
  make ,
}
/* Footer Not a pure module */
